language: node_js
node_js:
  - "9.11.1"
dist: trusty
sudo: false

branches:
  only:
  - gh-pages

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

install:
  - npm install -g yarn
  - npm install

script:
  - yarn build --base-href https://chathurangasandun.github.io/AngularCICDwithTravisGithubPagesDemo/
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: gh-pages